# Generated by Django 5.2.1 on 2025-05-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_id", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=50)),
            ],
        ),
    ]
